# Generated by Django 4.2.3 on 2023-09-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='data', max_length=30)),
                ('Content', models.CharField(default='data', max_length=70)),
                ('Created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ('-Updated_at',),
            },
        ),
        migrations.DeleteModel(
            name='restframework',
        ),
    ]
