# Generated by Django 4.2.3 on 2023-09-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bloginfo_delete_restframework'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogInfo',
            new_name='todo',
        ),
    ]
